services:
  nginx:
    depends_on:
      - frontend
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # ports:
    #   - '3000:3000'
    volumes:
      - /app/node_modules
    restart: on-failure