# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Golang CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_call:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.x'

    - name: Download module dependencies
      run: |
        cd backend
        go mod tidy

    - name: Install go linter
      run: |
        cd backend
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        
    - name: Run golangci-lint
      run: |
        cd backend
        golangci-lint run 
      
    - name: Build
      run: |
        cd backend
        go build -v backend/commands/server/

    # - name: Test
    #   run: go test -v ./...
